package constants

import "time"

// Challenge States
const (
	CHALLENGE_OPEN      = "CHALLENGEOPEN"
	CHALLENGE_STARTED   = "CHALLENGESTARTED"
	CHALLENGE_FORFEITED = "CHALLENGEFORFIETED"
	CHALLENGE_ENDED     = "CHALLENGEENDED"
	CHALLENGE_ABANDON   = "CHALLENGEABANDON"
)

// WebSocket Events
const (
	PING_SERVER          = "PING_SERVER"
	USER_JOINED          = "USER_JOINED"
	USER_LEFT            = "USER_LEFT"
	CREATOR_ABANDON      = "CREATOR_ABANDON"
	WS_CHALLENGE_STARTED = "CHALLENGE_STARTED"
	OWNER_LEFT           = "OWNER_LEFT"
	OWNER_JOINED         = "OWNER_JOINED"
	NEW_OWNER_ASSIGNED   = "NEW_OWNER_ASSIGNED"
	JOIN_CHALLENGE       = "JOIN_CHALLENGE"
	RETRIEVE_CHALLENGE   = "RETRIEVE_CHALLENGE"
	LEADERBOARD_UPDATE   = "LEADERBOARD_UPDATE"
	NEW_SUBMISSION       = "NEW_SUBMISSION"
	CURRENT_LEADERBOARD  = "CURRENT_LEADERBOARD"
)

const (
	BufferTime = 10 * time.Minute
)
